In [9]:
#Importar pacote pandas responsável por carregar e ler o conjunto de dados
import pandas as pd
data = pd.read_csv('wine_dataset.csv')

In [10]:
#retornar uma parte do conjunto de dados para visualização 
#head() = função para carregar primeiras linhas do conjunto
#variável sem função = carrega primeiras e últimas linhas do conjunto
data.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [11]:
#Substituir o texto por um número, para que o python consiga fazer os futuros cálculos e análises 
data['style'] = data['style'].replace('red', 0)

In [12]:
data['style'] = data['style'].replace('white',1)

In [13]:
#Separando as variáveis entre preditoras e variável alvo
y = data['style']

In [14]:
#Pega todas as colunas, exceto a varivável alvo(style)
#axis=0 (linhas) axis=1 (colunas)
x = data.drop('style', axis = 1)

In [28]:
from sklearn.model_selection import train_test_split

#Criação de conjunto de dados para teste e treino
#y = variavel alvo e x = preditoras

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [31]:
#Usado para identificar o número de linhas e colunas 
x_treino.shape

(4547, 12)

In [33]:
from sklearn.ensemble import ExtraTreesClassifier

#Criação do modelo 
model = ExtraTreesClassifier(n_estimators = 100)
#Os aprndizados serão aplicados a essas variáveis
model.fit(x_treino, y_treino)

#Percentual de aceito 
resultado = model.score(x_teste, y_teste)
print("Resultado:", resultado)

Resultado: 0.997948717948718

In [47]:
y_teste[0:9]

2592    1
2788    1
1554    0
4181    1
2656    1
5940    1
3121    1
5699    1
4752    1
Name: style, dtype: int64

In [44]:
x_teste[0:9]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2592,7.0,0.240,0.18,1.3,0.046,9.0,62.0,0.99400,3.38,0.47,10.100000,4
2788,7.6,0.260,0.47,1.6,0.068,5.0,55.0,0.99440,3.10,0.45,9.600000,5
1554,6.6,0.855,0.02,2.4,0.062,15.0,23.0,0.99627,3.54,0.60,11.000000,6
4181,6.8,0.180,0.30,12.8,0.062,19.0,171.0,0.99808,3.00,0.52,9.000000,7
2656,7.2,0.510,0.24,10.0,0.093,35.0,197.0,0.99810,3.41,0.47,9.000000,5
5940,7.4,0.270,0.52,15.7,0.054,36.0,139.0,0.99788,3.04,0.62,10.033333,6
3121,6.9,0.210,0.49,1.4,0.041,15.0,164.0,0.99270,3.25,0.63,11.000000,5
5699,6.3,0.290,0.23,14.2,0.037,24.0,99.0,0.99528,3.08,0.38,10.600000,6
4752,5.8,0.290,0.33,3.7,0.029,30.0,88.0,0.98994,3.25,0.42,12.300000,6

In [45]:
#preve o resultado alvo daquele determinado intervalo de dados preditor
previsao = model.predict(x_teste[0:9])

In [46]:
previsao

array([1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)